version: "2.3"

services:
    ntfy:
        image: binwiederhier/ntfy
        container_name: ntfy
        command:
            - serve
        environment:
            - TZ=UTC
        volumes:
            - /path/to/cache:/var/cache/ntfy
            - /path/to/etc:/etc/ntfy
        ports:
            - 80:80
        restart: unless-stopped
